In [2]:
import pandas as pd

In [5]:
from google.colab import files
uploaded = files.upload()

Saving nifty50_historical_data.csv to nifty50_historical_data.csv

In [6]:
df = pd.read_csv("nifty50_historical_data.csv")

In [8]:
df.shape

(287310, 25)

In [9]:
df.columns.tolist()

['Date',
 'Ticker',
 'Company_Name',
 'Sector',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume',
 'Dividend',
 'Stock_Split',
 'Daily_Return',
 'Volatility_20D',
 'MA_50',
 'MA_200',
 'Market_Cap',
 'PE_Ratio',
 'Forward_PE',
 'PEG_Ratio',
 'Price_to_Book',
 'Dividend_Yield',
 'EPS',
 'Beta',
 '52Week_High',
 '52Week_Low']

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287310 entries, 0 to 287309
Data columns (total 25 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Date            287310 non-null  object
 1   Ticker          287310 non-null  object
 2   Company_Name    287310 non-null  object
 3   Sector          287310 non-null  object
 4   Open            287310 non-null  float64
 5   High            287310 non-null  float64
 6   Low             287310 non-null  float64
 7   Close           287310 non-null  float64
 8   Volume          287310 non-null  int64
 9   Dividend        287310 non-null  float64
 10  Stock_Split     98 non-null      float64
 11  Daily_Return    287261 non-null  float64
 12  Volatility_20D  286330 non-null  float64
 13  MA_50           284909 non-null  float64
 14  MA_200          277559 non-null  float64
 15  Market_Cap      287310 non-null  int64
 16  PE_Ratio        281453 non-null  float64
 17  Forward_PE      287310 non-null  float64
 18  PEG_Ratio       0 non-null       float64
 19  Price_to_Book   287310 non-null  float64
 20  Dividend_Yield  281453 non-null  float64
 21  EPS             287310 non-null  float64
 22  Beta            283551 non-null  float64
 23  52Week_High     287310 non-null  float64
 24  52Week_Low      287310 non-null  float64
dtypes: float64(19), int64(2), object(4)
memory usage: 54.8+ MB

In [15]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.duplicated(['Date','Ticker']).sum()

np.int64(0)

In [22]:
df['Date'].dtype

dtype('O')

In [24]:
df['Date']= pd.to_datetime(df['Date'])

In [25]:
df['Date'].dtype

datetime64[ns, UTC+05:30]

In [27]:
df['Date'].head(10)

0   1999-01-01 00:00:00+05:30
1   1999-01-01 00:00:00+05:30
2   1999-01-01 00:00:00+05:30
3   1999-01-01 00:00:00+05:30
4   1999-01-01 00:00:00+05:30
5   1999-01-01 00:00:00+05:30
6   1999-01-01 00:00:00+05:30
7   1999-01-01 00:00:00+05:30
8   1999-01-01 00:00:00+05:30
9   1999-01-01 00:00:00+05:30
Name: Date, dtype: datetime64[ns, UTC+05:30]

In [30]:
df['Date']= pd.to_datetime(df['Date'].astype(str).str[:10])

In [32]:
df.isnull().sum()

Date                   0
Ticker                 0
Company_Name           0
Sector                 0
Open                   0
High                   0
Low                    0
Close                  0
Volume                 0
Dividend               0
Stock_Split       287212
Daily_Return          49
Volatility_20D       980
MA_50               2401
MA_200              9751
Market_Cap             0
PE_Ratio            5857
Forward_PE             0
PEG_Ratio         287310
Price_to_Book          0
Dividend_Yield      5857
EPS                    0
Beta                3759
52Week_High            0
52Week_Low             0
dtype: int64

In [33]:
df.head()

,Date,Ticker,Company_Name,Sector,Open,High,Low,Close,Volume,Dividend,...,Market_Cap,PE_Ratio,Forward_PE,PEG_Ratio,Price_to_Book,Dividend_Yield,EPS,Beta,52Week_High,52Week_Low
0,1999-01-01,AXISBANK.NS,Axis Bank Ltd.,Financials,2.198795,2.212041,2.139190,2.165681,337500,0.0,...,4257978515456,16.260086,13.534726,NaN,2.055485,0.07,84.28,0.313,1378.70,978.05
1,1999-01-01,BPCL.NS,Bharat Petroleum Corporation Ltd.,Energy,3.059547,3.083643,3.035450,3.073874,324744,0.0,...,1581385383936,6.329224,7.975497,NaN,1.658039,4.80,57.59,0.981,388.15,234.01
2,1999-01-01,BRITANNIA.NS,Britannia Industries Ltd.,FMCG,40.944134,40.974527,40.775792,40.845936,42000,0.0,...,1411608608768,60.977005,48.923096,NaN,37.810410,1.28,96.11,0.572,6336.00,4506.00
3,1999-01-01,CIPLA.NS,Cipla Ltd.,Pharma,19.149712,19.580167,19.006226,19.426748,108750,0.0,...,1069501579264,23.529411,23.371544,NaN,3.248832,0.98,56.27,0.042,1673.00,1281.70
4,1999-01-01,DRREDDY.NS,Dr. Reddy's Laboratories Ltd.,Pharma,21.000834,21.293348,21.000834,21.185806,2324000,0.0,...,1014151315456,17.929054,22.147236,NaN,2.723533,0.66,67.94,0.315,1379.70,1020.00

In [34]:
print("Start Date:",df['Date'].min())
print("End Date:",df['Date'].max())

Start Date: 1999-01-01 00:00:00
End Date: 2026-01-30 00:00:00

In [35]:
df['Sector'].unique()

array(['Financials', 'Energy', 'FMCG', 'Pharma', 'Automobile', 'Metals',
       'IT', 'Consumer Durables', 'Cement', 'Infrastructure',
       'Healthcare', 'Telecom', 'Power'], dtype=object)

In [36]:
df['Sector'].nunique()

13

In [38]:
df['Sector'].value_counts()

Sector
Financials           53903
FMCG                 32903
IT                   32345
Automobile           30842
Pharma               25983
Metals               22935
Energy               20301
Cement               17798
Infrastructure       16199
Consumer Durables    12626
Power                 9763
Healthcare            5856
Telecom               5856
Name: count, dtype: int64

In [39]:
print(df['Sector'].value_counts())

Sector
Financials           53903
FMCG                 32903
IT                   32345
Automobile           30842
Pharma               25983
Metals               22935
Energy               20301
Cement               17798
Infrastructure       16199
Consumer Durables    12626
Power                 9763
Healthcare            5856
Telecom               5856
Name: count, dtype: int64

In [40]:
df['Company_Name'].nunique()

49

In [41]:
df['Company_Name'].head()

0                       Axis Bank Ltd.
1    Bharat Petroleum Corporation Ltd.
2            Britannia Industries Ltd.
3                           Cipla Ltd.
4        Dr. Reddy's Laboratories Ltd.
Name: Company_Name, dtype: object

In [42]:
df[['Open','High','Low','Close']].head()

        Open       High        Low      Close
0   2.198795   2.212041   2.139190   2.165681
1   3.059547   3.083643   3.035450   3.073874
2  40.944134  40.974527  40.775792  40.845936
3  19.149712  19.580167  19.006226  19.426748
4  21.000834  21.293348  21.000834  21.185806

In [43]:
df[['Open','High','Low','Close']].isnull().sum()

Open     0
High     0
Low      0
Close    0
dtype: int64

In [44]:
print("High < Open:",(df['High']<df['Open']).sum())
print("Low > Open:",(df['Low']>df['Open']).sum())
print("Close > Open:",(df['Close']>df['Open']).sum())
print("Close < Open:",(df['Close']<df['Open']).sum())
#

High < Open: 26
Low > Open: 41
Close > Open: 131168
Close < Open: 150828

In [45]:
df[df['Low']>df['Open']][['Date','Ticker','Open','High','Low','Close']]

            Date       Ticker      Open      High       Low     Close
18740 2002-07-01  ADANIENT.NS -0.012187 -0.012522 -0.011920 -0.012173
18773 2002-07-02  ADANIENT.NS -0.012385 -0.012426 -0.012118 -0.012269
18806 2002-07-03  ADANIENT.NS -0.012255 -0.012392 -0.012194 -0.012269
18872 2002-07-05  ADANIENT.NS -0.012406 -0.012406 -0.012262 -0.012310
18905 2002-07-08  ADANIENT.NS -0.012461 -0.012995 -0.012194 -0.012851
18938 2002-07-09  ADANIENT.NS -0.012803 -0.012871 -0.012433 -0.012515
18971 2002-07-10  ADANIENT.NS -0.012597 -0.012597 -0.012392 -0.012502
19004 2002-07-11  ADANIENT.NS -0.012947 -0.012947 -0.012262 -0.012296
19037 2002-07-12  ADANIENT.NS -0.012433 -0.012536 -0.012324 -0.012392
19070 2002-07-15  ADANIENT.NS -0.012255 -0.012317 -0.012091 -0.012139
19136 2002-07-17  ADANIENT.NS -0.012255 -0.012255 -0.012118 -0.012152
19169 2002-07-18  ADANIENT.NS -0.012481 -0.012481 -0.012194 -0.012296
19202 2002-07-19  ADANIENT.NS -0.012392 -0.012392 -0.012125 -0.012248
19235 2002-07-22  ADANIENT.NS -0.012050 -0.012303 -0.011879 -0.011961
19301 2002-07-24  ADANIENT.NS -0.011844 -0.012002 -0.011646 -0.011646
19334 2002-07-25  ADANIENT.NS -0.011981 -0.012166 -0.011571 -0.011755
19367 2002-07-26  ADANIENT.NS -0.011468 -0.011468 -0.011310 -0.011393
19400 2002-07-29  ADANIENT.NS -0.011571 -0.011571 -0.010975 -0.011112
19433 2002-07-30  ADANIENT.NS -0.011571 -0.011571 -0.010954 -0.010989
19466 2002-07-31  ADANIENT.NS -0.011160 -0.011160 -0.010680 -0.010886
19532 2002-08-02  ADANIENT.NS -0.010954 -0.010954 -0.010728 -0.010906
19565 2002-08-05  ADANIENT.NS -0.011502 -0.011502 -0.010694 -0.010886
19598 2002-08-06  ADANIENT.NS -0.010954 -0.010954 -0.010687 -0.010735
19631 2002-08-07  ADANIENT.NS -0.011091 -0.011091 -0.010852 -0.010934
19664 2002-08-08  ADANIENT.NS -0.011160 -0.011160 -0.010715 -0.010769
19697 2002-08-09  ADANIENT.NS -0.010817 -0.010920 -0.010749 -0.010852
19730 2002-08-12  ADANIENT.NS -0.010893 -0.010947 -0.010817 -0.010900
19768 2002-08-13  ADANIENT.NS -0.010913 -0.010947 -0.010817 -0.010858
19806 2002-08-14  ADANIENT.NS -0.010927 -0.010927 -0.010633 -0.010749
19882 2002-08-16  ADANIENT.NS -0.010722 -0.010817 -0.010516 -0.010578
19920 2002-08-19  ADANIENT.NS -0.010817 -0.010817 -0.010482 -0.010571
19958 2002-08-20  ADANIENT.NS -0.010674 -0.010674 -0.010544 -0.010564
19996 2002-08-21  ADANIENT.NS -0.010701 -0.010769 -0.010612 -0.010667
20034 2002-08-22  ADANIENT.NS -0.010701 -0.010783 -0.010612 -0.010701
20072 2002-08-23  ADANIENT.NS -0.010756 -0.010817 -0.010612 -0.010735
20110 2002-08-26  ADANIENT.NS -0.010811 -0.010954 -0.010660 -0.010701
20148 2002-08-27  ADANIENT.NS -0.010735 -0.010797 -0.010578 -0.010639
20186 2002-08-28  ADANIENT.NS -0.010749 -0.010749 -0.010585 -0.010660
20224 2002-08-29  ADANIENT.NS -0.010680 -0.010680 -0.010544 -0.010598
20262 2002-08-30  ADANIENT.NS -0.010598 -0.010646 -0.010550 -0.010626
20338 2002-09-03  ADANIENT.NS -0.010749 -0.010763 -0.010633 -0.010715

In [46]:
price_columns =['Open','High','Low','Close']
(df[price_columns] < 0 ).sum()

Open     47
High     47
Low      47
Close    47
dtype: int64

In [55]:
df[df[price_columns].lt(0).any(axis=1)][['Date','Ticker','Company_Name','Open','High','Low','Close']].head()

,Date,Ticker,Company_Name,Open,High,Low,Close
18740,2002-07-01,ADANIENT.NS,Adani Enterprises Ltd.,-0.012187,-0.012522,-0.011920,-0.012173
18773,2002-07-02,ADANIENT.NS,Adani Enterprises Ltd.,-0.012385,-0.012426,-0.012118,-0.012269
18806,2002-07-03,ADANIENT.NS,Adani Enterprises Ltd.,-0.012255,-0.012392,-0.012194,-0.012269
18839,2002-07-04,ADANIENT.NS,Adani Enterprises Ltd.,-0.012324,-0.012522,-0.012324,-0.012337
18872,2002-07-05,ADANIENT.NS,Adani Enterprises Ltd.,-0.012406,-0.012406,-0.012262,-0.012310

In [57]:
price_columns =['Open','High','Low','Close']
df=df[(df['Open']>0)&(df['High']>0)&(df['Low']>0)&(df['Close']>0)].copy()

In [58]:
print("Rows after cleaning",len(df))

Rows after cleaning 287263

In [61]:
df[df['High']< df['Close']][['Date','Ticker','Company_Name','Open','High','Low','Close']].head()

,Date,Ticker,Company_Name,Open,High,Low,Close
114,1999-01-08,SBIN.NS,State Bank of India,11.040163,11.585897,10.892752,11.585897
205,1999-01-15,EICHERMOT.NS,Eicher Motors Ltd.,0.695380,0.701224,0.683693,0.701224
232,1999-01-18,ONGC.NS,Oil & Natural Gas Corporation Ltd.,4.989097,5.145987,4.894963,5.145987
325,1999-01-25,EICHERMOT.NS,Eicher Motors Ltd.,0.657397,0.701224,0.657397,0.701224
345,1999-01-26,EICHERMOT.NS,Eicher Motors Ltd.,0.701224,0.701224,0.701224,0.701224

In [64]:
df [df['Low']>df['Close']][['Date','Ticker','Company_Name','Open','High','Low','Close']].head()

,Date,Ticker,Company_Name,Open,High,Low,Close
276,1999-01-20,TATACONSUM.NS,Tata Consumer Products Ltd.,21.444075,21.444075,21.444075,21.444075
356,1999-01-26,TATACONSUM.NS,Tata Consumer Products Ltd.,22.074440,22.074440,22.074440,22.074440
433,1999-02-01,RELIANCE.NS,Reliance Industries Ltd.,6.620322,6.683253,6.469288,6.469288
436,1999-02-01,TATACONSUM.NS,Tata Consumer Products Ltd.,22.239387,22.239387,21.455853,21.455853
542,1999-02-09,BRITANNIA.NS,Britannia Industries Ltd.,53.062309,53.261044,52.419338,52.419338

In [65]:
price_columns = ['Open','High','Low', 'Close']
valid_ohlc = ((df['High']>= df['Open'])&
(df['High']>= df['Close'])&
(df['Low']<= df['Open'])&
(df['Low']<= df['Close']))
df_clean = df[valid_ohlc].copy()
print ("Original rows", len(df))
print ("Clean rows", len(df_clean))
print("Removed rows", len(df_clean))

Original rows 287263
Clean rows 287113
Removed rows 287113

In [69]:
print("High < Open",(df_clean['High']<df_clean['Open']).sum())
print("High < Close",(df_clean['High']<df_clean['Close']).sum())
print("Low > Open",(df_clean['Low']>df_clean['Open']).sum())
print("Low > Close",(df_clean['Low']>df_clean['Close']).sum())

High < Open 0
High < Close 0
Low > Open 0
Low > Close 0

In [73]:
price_columns = ['Open','Low','High','Close']
print ("Negative valuse:")
print ((df_clean[price_columns]< 0).sum())

Negative valuse:
Open     0
Low      0
High     0
Close    0
dtype: int64

In [74]:
print("Missing values:")
print (df_clean[price_columns].isnull().sum())

Missing values:
Open     0
Low      0
High     0
Close    0
dtype: int64

In [75]:
print("Duplicate rows:",df_clean.duplicated().sum())

Duplicate rows: 0